{{- if .Values.cainjector.enabled }}
{{- if and (.Values.global.podSecurityPolicy.enabled) (.Capabilities.APIVersions.Has "policy/v1beta1") }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cainjector.fullname" . }}-psp
  labels:
    app: {{ include "cainjector.name" . }}
    app.kubernetes.io/name: {{ include "cainjector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "cainjector"
    {{- include "labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "cainjector.fullname" . }}
{{- end }}
{{- end }}
