apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.clusterissuer.name }}
  labels:
    {{- include "issuerLabels" . | nindent 4 }}
  annotations:
    {{- include "issuerAnnotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "issuerLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
