{{- with .Values.webhook.podLogs }}
{{- if .enabled }}
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: {{ include "webhook.fullname" $ }}
  namespace: {{ include "cert-manager.namespace" $ }}
  labels:
    app: {{ include "webhook.name" $ }}
    app.kubernetes.io/name: {{ include "webhook.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: "webhook"
    {{- include "labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ include "cert-manager.namespace" $ }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webhook.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: "webhook"
  relabelings:
  - action: replace
    replacement: {{ coalesce .tenant $.Values.global.tenant }}
    targetLabel: giantswarm_observability_tenant
    {{- with .relabelings }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
