apiVersion: v2
name: cert-manager-app
description: Simplifies the process of obtaining, renewing and using certificates.
version: 3.8.2
home: https://github.com/giantswarm/cert-manager-app
icon: https://s.giantswarm.io/app-icons/cert-manager/1/light.svg
appVersion: v1.16.2

sources:
- https://github.com/cert-manager/cert-manager
annotations:
  application.giantswarm.io/team: shield
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Shield
dependencies:
  - name: cert-manager
    version: 1.16.2
  - name: cert-manager-giantswarm-clusterissuer
    version: 2.0.0
    alias: giantSwarmClusterIssuer
  - name: cert-manager-giantswarm-netpol
    version: 0.1.0
    condition: giantswarmNetworkPolicy.enabled
  - name: cert-manager-giantswarm-ciliumnetworkpolicies
    version: 0.1.0
    condition: ciliumNetworkPolicy.enabled
