apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: cert-manager
    git:
      url: https://github.com/giantswarm/cert-manager-upstream
      ref: vendir
    includePaths:
    - deploy/charts/cert-manager/**/*
    newRootPath: deploy/charts/cert-manager
- path: helm/cert-manager
  contents:
  - path: .
    directory:
      path: vendor/cert-manager
    includePaths:
    - templates/**/*
    ignorePaths:
    - values.schema.json
    - values.yaml
    - .helmignore
    - .kube-linter.yaml
    - Chart.lock
    - Chart.yaml
    - Chart.template.yaml
