apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: cert-manager
    git:
      url: https://github.com/giantswarm/cert-manager-upstream
      ref: crd-labels
    includePaths:
    - deploy/charts/cert-manager/**/*
    newRootPath: deploy/charts/cert-manager
- path: helm/cert-manager/templates
  contents:
  - path: .
    directory:
      path: vendor/cert-manager/templates
