apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "certManager.name.webhook" . }}--dynamic-serving
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "webhook"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
  - '{{ template "certManager.name.webhook" . }}-ca'
  verbs: ["get", "list", "watch", "update"]
# It's not possible to grant CREATE permission on a single resourceName.
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "certManager.name.webhook" . }}--dynamic-serving
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "webhook"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "certManager.name.webhook" . }}--dynamic-serving
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ template "certManager.name.webhook" . }}
  namespace: {{ .Release.Namespace | quote }}
