# Default values for cert-manager-giantswarm-clusterissuer chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: cert-manager-giantswarm-clusterissuer

userID: 1000
groupID: 1000

# this should be higher than the default (6) in order to ensure
# that the job is not marked as failed if it runs too soon after
# the webhook pod has been created.
backoffLimit: 10

image:
  registry: quay.io
  name: giantswarm/docker-kubectl
  tag: latest

resources:
  requests:
    cpu: 50m
    memory: 75Mi
