version: 2.1
orbs:
  architect: giantswarm/architect@4.24.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "cert-manager-app"
          persist_chart_archive: true
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "cert-manager-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-cert-manager-app-to-control-plane-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cert-manager-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      # deploy to all installations (only tags)
      - architect/push-to-app-collection:
          name: push-cert-manager-app-to-shared-app-collection
          app_name: "cert-manager-app"
          app_namespace: "kube-system"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-cert-manager-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to aws installations (only tags)
      - architect/push-to-app-collection:
          name: push-cert-manager-app-to-aws-app-collection
          app_name: "cert-manager-app"
          app_namespace: "kube-system"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-cert-manager-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to azure installations (only tags)
      - architect/push-to-app-collection:
          name: push-cert-manager-app-to-azure-app-collection
          app_name: "cert-manager-app"
          app_namespace: "kube-system"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-cert-manager-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to openstack installations (only tags)
      - architect/push-to-app-collection:
          name: push-cert-manager-app-to-openstack-app-collection
          app_name: "cert-manager-app"
          app_namespace: "kube-system"
          app_collection_repo: "openstack-app-collection"
          requires:
            - push-cert-manager-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to kvm installations (only tags)
      - architect/push-to-app-collection:
          name: push-cert-manager-app-to-kvm-app-collection
          app_name: "cert-manager-app"
          app_namespace: "kube-system"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-cert-manager-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to vsphere installations (only tags)
      - architect/push-to-app-collection:
          name: push-cert-manager-app-to-vsphere-app-collection
          app_name: "cert-manager-app"
          app_namespace: "kube-system"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-cert-manager-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-default-app-catalog
