{{- if .Values.global.giantSwarmClusterIssuer.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
data:
  clusterissuer: |
{{ .Files.Get "misc/clusterissuers.yaml" | indent 4 }}
{{- end }}
