apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "cert-manager.fullname" . }}-allow-egress
  namespace: {{ include "cert-manager.namespace" . }}
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 9402
      protocol: TCP
    - port: 9403
      protocol: TCP
  podSelector:
    matchLabels:
      app: {{ template "cert-manager.name" . }}
      app.kubernetes.io/name: {{ template "cert-manager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "controller"
  policyTypes:
  - Ingress
  - Egress
