apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "certManager.name.cainjector" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "cainjector"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
