apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "certManager.name.cainjector" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "cainjector"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cainjector.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "cainjector"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "cainjector"
        {{- include "certManager.defaultLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "certManager.name.cainjector" . }}
      securityContext:
        runAsUser: {{ .Values.global.securityContext.userID }}
        runAsGroup: {{ .Values.global.securityContext.groupID }}
      containers:
        - name: cainjector
          image: "{{ .Values.global.image.registry }}/giantswarm/cert-manager-cainjector:v0.15.2"
          imagePullPolicy: {{ .Values.cainjector.image.pullPolicy }}
          args:
          - --v={{ .Values.cainjector.logLevel | default 2 }}
          - --leader-election-namespace={{ .Release.Namespace }}
          {{- if .Values.cainjector.extraArgs }}
          {{ toYaml .Values.cainjector.extraArgs }}
          {{- end }}
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.cainjector.resources | nindent 12 }}
