{{- $proxy := deepCopy .Values.cluster.proxy |  mustMerge .Values.proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "certManager.name.cainjector" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: cainjector
    giantswarm.io/monitoring_basic_sli: "true"
spec:
  selector:
    matchLabels:
      {{- include "certManager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cainjector
  replicas: {{ .Values.cainjector.replicas }}
  template:
    metadata:
      labels:
        {{- include "certManager.defaultLabels" . | nindent 8 }}
        app.kubernetes.io/component: cainjector
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      serviceAccountName: {{ template "certManager.name.cainjector" . }}
      securityContext:
        runAsUser: {{ .Values.global.securityContext.userID }}
        runAsGroup: {{ .Values.global.securityContext.groupID }}
        runAsNonRoot: {{ .Values.global.securityContext.runAsNonRoot }}
      containers:
      - name: cainjector
        image: "{{ .Values.global.image.registry }}/giantswarm/cert-manager-cainjector:{{ .Values.global.image.version }}"
        imagePullPolicy: {{ .Values.cainjector.image.pullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
        args:
        - --v={{ .Values.cainjector.logLevel | default 2 }}
        - --leader-election-namespace={{ .Release.Namespace }}
        {{- if .Values.cainjector.extraArgs }}
        {{- toYaml .Values.cainjector.extraArgs | nindent 8 }}
        {{- end }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if and $proxy.noProxy $proxy.http $proxy.https }}
        - name: NO_PROXY
          value: {{ $proxy.noProxy }}
        - name: no_proxy
          value: {{ $proxy.noProxy }}
        - name: HTTP_PROXY
          value: {{ $proxy.http }}
        - name: http_proxy
          value: {{ $proxy.http }}
        - name: HTTPS_PROXY
          value: {{ $proxy.https }}
        - name: https_proxy
          value: {{ $proxy.https }}
        {{- end }}
        resources: {{- toYaml .Values.cainjector.resources | nindent 10 }}
