apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "certManager.name.cainjector" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: cainjector
    {{- with .Values.cainjector.serviceAccount.labels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.cainjector.serviceAccount.automountServiceAccountToken }}
