{{- $proxy := deepCopy .Values.cluster.proxy |  mustMerge .Values.proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "certManager.name.cainjector" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "cainjector"
    giantswarm.io/monitoring_basic_sli: "true"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cainjector.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "cainjector"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "cainjector"
        {{- include "certManager.defaultLabels" . | nindent 8 }}
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      serviceAccountName: {{ template "certManager.name.cainjector" . }}
      securityContext:
        runAsUser: {{ .Values.global.securityContext.userID }}
        runAsGroup: {{ .Values.global.securityContext.groupID }}
        runAsNonRoot: {{ .Values.global.securityContext.runAsNonRoot }}
      containers:
        - name: cainjector
          image: "{{ .Values.global.image.registry }}/giantswarm/cert-manager-cainjector:{{ .Values.global.image.version }}"
          imagePullPolicy: {{ .Values.cainjector.image.pullPolicy }}
          args:
          - --v={{ .Values.cainjector.logLevel | default 2 }}
          - --leader-election-namespace={{ .Release.Namespace }}
          {{- if .Values.cainjector.extraArgs }}
          {{ toYaml .Values.cainjector.extraArgs }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if and $proxy.noProxy $proxy.http $proxy.https }}
          - name: NO_PROXY
            value: {{ $proxy.noProxy }}
          - name: no_proxy
            value: {{ $proxy.noProxy }}
          - name: HTTP_PROXY
            value: {{ $proxy.http }}
          - name: http_proxy
            value: {{ $proxy.http }}
          - name: HTTPS_PROXY
            value: {{ $proxy.https }}
          - name: https_proxy
            value: {{ $proxy.https }}
          {{- end }}
          resources:
            {{- toYaml .Values.cainjector.resources | nindent 12 }}
