apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "certManager.name.cainjector" . }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: cainjector
spec:
  privileged: false
  hostPID: false
  hostIPC: false
  hostNetwork: false
  volumes:
  - downwardAPI
  - secret
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: {{ .Values.global.securityContext.groupID }}
      max: {{ .Values.global.securityContext.groupID }}
  readOnlyRootFilesystem: true
  runAsUser:
    rule: MustRunAs
    ranges:
    - min: {{ .Values.global.securityContext.userID }}
      max: {{ .Values.global.securityContext.userID }}
  runAsGroup:
    rule: MustRunAs
    ranges:
    - min: {{ .Values.global.securityContext.groupID }}
      max: {{ .Values.global.securityContext.groupID }}
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: {{ .Values.global.securityContext.groupID }}
      max: {{ .Values.global.securityContext.groupID }}
  allowPrivilegeEscalation: false
  seLinux:
    rule: RunAsAny
