apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.cainjector.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "certManager.name.cainjector" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "cainjector"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    {{- with .Values.cainjector.serviceAccount.labels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
