{{- if .Values.global.giantSwarmClusterIssuer.install }}
{{- if and (eq .Values.Installation.V1.GiantSwarm.CertManager.AcmeSolver "dns01") (ne .Values.Installation.V1.Secret.Cloudflare.Token "") }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: kube-system
type: Opaque
stringData:
  api-token: {{ .Values.Installation.V1.Secret.Cloudflare.Token }}
{{- end }}
{{- end }}
