kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "certManager.name" . }}-controller-np
  labels:
    app.kubernetes.io/component: "controller"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: "controller"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
  # allow all egress traffic
  egress:
  - {}
  # explicitly deny ingress traffic
  ingress: []
  policyTypes:
  - Ingress
  - Egress
