apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "certManager.name.controller" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  podSelector:
    matchLabels:
      {{- include "certManager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
