apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "certManager.name.controller" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "controller"
    giantswarm.io/monitoring_basic_sli: "true"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "controller"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "controller"
        {{- include "certManager.defaultLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.prometheus.enabled  }}
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9402'
      {{- end }}
      {{- if .Values.controller.aws.role }}
        iam.amazonaws.com/role: {{ .Values.controller.aws.role }}
      {{- end }}
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: {{ template "certManager.name.controller" . }}
      securityContext:
        runAsUser: {{ .Values.global.securityContext.userID }}
        runAsGroup: {{ .Values.global.securityContext.groupID }}
      containers:
        - name: cert-manager
          image: "{{ .Values.global.image.registry }}/giantswarm/cert-manager-controller:{{ .Values.global.image.version }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          args:
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace={{ .Release.Namespace }}
          - --v={{ .Values.controller.logLevel | default 2 }}
          {{- if or (.Values.controller.defaultIssuer) (.Values.global.giantSwarmClusterIssuer.install) }}
          - --default-issuer-name={{ .Values.controller.defaultIssuer.name }}
          - --default-issuer-kind={{ .Values.controller.defaultIssuer.kind }}
          - --default-issuer-group={{ .Values.controller.defaultIssuer.group }}
          {{- end }}
          {{- if eq .Values.global.acmeSolver.type "dns01" }}
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers="{{ .Values.global.acmeSolver.DNSServer }}:53"
          {{- end }}
          {{- if .Values.global.enableCertOwnerRef }}
          - --enable-certificate-owner-ref=true
          {{- end }}
          {{- if .Values.controller.extraArgs }}
          {{ toYaml .Values.controller.extraArgs }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
          ports:
          - containerPort: 9402
            protocol: TCP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
