apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "certManager.name.controller" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: "controller"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
