{{- if .Capabilities.APIVersions.Has "policy/v1beta1" }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "certManager.name.controller" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "controller"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
  {{- if .Values.securityContext.seccompProfile }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "*"
  {{- end }}
spec:
  allowedCapabilities: [] # drop default capabilities
  allowPrivilegeEscalation: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'downwardAPI'
    - 'secret'
    - 'projected'
{{- end }}
