apiVersion: v1
kind: Service
metadata:
  name: {{ template "certManager.name.controller" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    giantswarm.io/monitoring-path: "/metrics"
    giantswarm.io/monitoring-port: "9402"
    giantswarm.io/monitoring-app-label: {{ .Chart.Name | quote }}
  labels:
    app.kubernetes.io/component: "controller"
    giantswarm.io/monitoring: "true"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9402
      targetPort: 9402
  selector:
    app.kubernetes.io/component: "controller"
    {{- include "certManager.selectorLabels" . | nindent 4 }}
