apiVersion: v1
kind: Service
metadata:
  name: {{ template "certManager.name.controller" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    giantswarm.io/monitoring: "true"
  annotations:
    giantswarm.io/monitoring-app-label: {{ .Chart.Name }}
    giantswarm.io/monitoring-port: "9402"
    giantswarm.io/monitoring-path: /metrics
spec:
  type: ClusterIP
  selector:
    {{- include "certManager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
  - protocol: TCP
    port: 9402
