{{- if .Values.global.crds.install }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "certManager.name.crdInstall" . }}"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  - clusterissuers
  verbs:
  - "create"
  - "delete"
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - "create"
  - "delete"
  - "get"
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "certManager.name.crdInstall" . }}
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "certManager.name.crdInstall" . }}"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "certManager.name.crdInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "certManager.name.crdInstall" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
