{{- if .Values.global.giantSwarmClusterIssuer.install }}
{{- if and (eq .Values.global.acmeSolver.type "dns01") (eq .Values.global.acmeSolver.provider "route53") (ne .Values.global.acmeSolver.secret.route53.secretAccessKey "") }}
apiVersion: v1
kind: Secret
metadata:
  name: route53-access-key-secret 
  namespace: kube-system
type: Opaque
stringData:
  secret-access-key: {{ .Values.global.acmeSolver.secret.route53.secretAccessKey }}
{{- end }}
{{- end }}
