{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "startupapicheck.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "startupapicheck.name" . }}
    app.kubernetes.io/name: {{ include "startupapicheck.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "startupapicheck"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: "startupapicheck"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
{{ end }}
