{{- if .Values.startupapicheck.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "startupapicheck.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: startupapicheck
spec:
  podSelector:
    matchLabels:
      {{- include "certManager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: startupapicheck
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
{{- end }}
