apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "certManager.name.webhook" . }}
  labels:
    app.kubernetes.io/component: "webhook"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from-secret: "{{ .Release.Namespace }}/{{ template "certManager.name.webhook" . }}-ca"
  {{- if .Values.webhook.mutatingWebhookConfigurationAnnotations }}
{{ toYaml .Values.webhook.mutatingWebhookConfigurationAnnotations | indent 4 }}
  {{- end }}
webhooks:
  - name: webhook.cert-manager.io
    rules:
      - apiGroups:
          - "cert-manager.io"
          - "acme.cert-manager.io"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "*/*"
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    failurePolicy: Fail
    # Only include 'sideEffects' field in Kubernetes 1.12+
    sideEffects: None
    clientConfig:
      service:
        name: {{ template "certManager.name.webhook" . }}
        namespace: {{ .Release.Namespace | quote }}
        path: /mutate
