{{- if .Values.webhook.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "certManager.name.webhook" . }}
  labels:
    app.kubernetes.io/component: "webhook"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  {{- if .Values.webhook.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.webhook.podDisruptionBudget.minAvailable }}
  {{- else if .Values.webhook.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.webhook.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "webhook"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
{{- end }}
