apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "certManager.name.webhook" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "webhook"
    giantswarm.io/monitoring_basic_sli: "true"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "webhook"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "webhook"
        {{- include "certManager.defaultLabels" . | nindent 8 }}
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: {{ template "certManager.name.webhook" . }}
      securityContext:
        runAsUser: {{ .Values.global.securityContext.userID }}
        runAsGroup: {{ .Values.global.securityContext.groupID }}
        runAsNonRoot: {{ .Values.global.securityContext.runAsNonRoot }}
      containers:
        - name: webhook
          image: "{{ .Values.global.image.registry }}/giantswarm/cert-manager-webhook:{{ .Values.global.image.version }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          args:
          - --v={{ .Values.webhook.logLevel | default 2 }}
          - --secure-port={{ .Values.webhook.securePort }}
          - --dynamic-serving-ca-secret-namespace={{ .Release.Namespace }}
          - --dynamic-serving-ca-secret-name={{ template "certManager.name.webhook" . }}-ca
          - --dynamic-serving-dns-names={{ template "certManager.name.webhook" . }},{{ template "certManager.name.webhook" . }}.{{ .Release.Namespace }},{{ template "certManager.name.webhook" . }}.{{ .Release.Namespace }}.svc
          securityContext:
            readOnlyRootFilesystem: true
          ports:
          - name: https
            containerPort: {{ .Values.webhook.securePort }}
          livenessProbe:
            httpGet:
              path: /livez
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
