apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "webhook"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: "webhook"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "webhook"
        {{- include "certManager.defaultLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "certManager.name" . }}-webhook
      containers:
        - name: {{ template "certManager.name" . }}-webhook
          image: "{{ .Values.global.image.registry }}/{{ .Values.webhook.image.name }}:{{ .Values.webhook.image.tag }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          args:
          - --v=2
          - --secure-port=10250
          - --dynamic-serving-ca-secret-namespace={{ .Release.Namespace }}
          - --dynamic-serving-ca-secret-name={{ template "certManager.name" . }}-webhook-ca
          - --dynamic-serving-dns-names={{ template "certManager.name" . }}-webhook,{{ template "certManager.name" . }}-webhook.{{ .Release.Namespace }},{{ template "certManager.name" . }}-webhook.{{ .Release.Namespace }}.svc
          ports:
          - name: https
            containerPort: 10250
          livenessProbe:
            httpGet:
              path: /livez
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
