apiVersion: v1
kind: Service
metadata:
  name: {{ template "certManager.name" . }}-webhook
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "webhook"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 10250
  selector:
    app.kubernetes.io/component: "webhook"
    {{- include "certManager.selectorLabels" . | nindent 4 }}
