{{- if and .Values.acme.dns01.azureDNS.enabled (not (empty .Values.acme.dns01.azureDNS.clientSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: azuredns-config
type: Opaque
data:
  client-secret: {{ .Values.acme.dns01.azureDNS.clientSecret | b64enc | quote }}
{{- end }}
