apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "issuerLabels" . | nindent 4 }}
  annotations:
    {{- include "issuerAnnotations" . | nindent 4 }}
rules:
{{- if .Capabilities.APIVersions.Has "policy/v1beta1" }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.name }}
  verbs:
  - use
{{ end }}
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
