apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "issuerLabels" . | nindent 4 }}
  annotations:
    {{- include "issuerAnnotations" . | nindent 4 }}
    helm.sh/hook-weight: "1"
    "ignore-check.kube-linter.io/no-read-only-root-fs": "kubectl writes temporary files"
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "issuerLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: update-ingress-script
        command:
        - /bin/sh
        args:
        - /scripts/update-ingress.sh
        image: '{{ include "registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
        imagePullPolicy: Always
        volumeMounts:
        - name: {{ .Values.name }}-script-volume
          mountPath: /scripts
        - name: {{ .Values.name }}
          subPath: clusterissuer.yaml
          mountPath: /data/clusterissuer.yaml
      containers:
      - name: {{ .Values.name }}
        image: '{{ include "registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
        imagePullPolicy: Always
        args:
        - apply
        - --filename
        - /data
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsUser: {{ .Values.userID }}
          runAsGroup: {{ .Values.groupID }}
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: {{ .Values.name }}
        configMap:
          name: {{ .Values.name }}
      - name: {{ .Values.name }}-script-volume
        configMap:
          name: {{ .Values.name }}-script
      restartPolicy: Never
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
