{{- if .Values.acme.dns01.route53.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: route53-access-key-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  secret-access-key: {{ .Values.acme.dns01.route53.secretAccessKey }}
{{- end }}
