apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
rules:
# allow hook to get/list all cm,sa
- apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
  verbs:
  - "get"
  - "list"
# allow hook to delete only the crdinstall cm
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}-certificaterequests"
  - "{{ template "certManager.name.crdInstall" . }}-certificates"
  - "{{ template "certManager.name.crdInstall" . }}-challenges"
  - "{{ template "certManager.name.crdInstall" . }}-clusterissuers"
  - "{{ template "certManager.name.crdInstall" . }}-issuers"
  - "{{ template "certManager.name.crdInstall" . }}-orders"
# allow hook to delete only the crdinstall sa
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs:
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
# allow hook to get/list all jobs
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "get"
  - "list"
# allow hook to delete only the crdinstall job
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
# allow hook to get/list all netpol
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "get"
  - "list"
# allow hook to delete only the crdinstall netpol
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
# allow hook to get/list all psp
- apiGroups:
  - "policy"
  resources:
  - "podsecuritypolicies"
  verbs:
  - "get"
  - "list"
# allow hook to delete only the crdinstall psp
- apiGroups:
  - "policy"
  resources:
  - "podsecuritypolicies"
  verbs:
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
# allow hook to get/list all clusterrole/clusterrolebinding
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterroles"
  - "clusterrolebindings"
  verbs:
  - "get"
  - "list"
# allow hook to delete only the crdinstall clusterrole/clusterrolebinding
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterroles"
  - "clusterrolebindings"
  verbs:
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
# allow hook to use its own psp
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.name }}
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
