apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
# allow deletion of all resource types created by crd-install hook
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
  verbs:
  - "get"
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "get"
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
- apiGroups:
  - "policy"
  resources:
  - "networkpolicies"
  - "podsecuritypolicies"
  verbs:
  - "get"
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterroles"
  - "clusterrolebindings"
  verbs:
  - "get"
  - "delete"
  resourceNames:
  - "{{ template "certManager.name.crdInstall" . }}"
# allow the role to use the subchart's PSP
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.name }}
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
