apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook-weight": "-4"
    {{ include "CRDCleanupAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
