{{- if .Values.crds.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "certManager.name.crdInstall" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "certManager.name.crdInstall" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
