{{- if .Values.crds.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "certManager.name.crdInstall" . }}-certificaterequests
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
data:
  certificaterequests.yaml: |
{{ tpl ( .Files.Get "files/certificaterequests.yaml" ) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "certManager.name.crdInstall" . }}-certificates
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
data:
  certificates.yaml: |
{{ tpl ( .Files.Get "files/certificates.yaml" ) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "certManager.name.crdInstall" . }}-challenges
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
data:
  challenges.yaml: |
{{ tpl ( .Files.Get "files/challenges.yaml" ) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "certManager.name.crdInstall" . }}-clusterissuers
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
data:
  clusterissuers.yaml: |
{{ tpl ( .Files.Get "files/clusterissuers.yaml" ) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "certManager.name.crdInstall" . }}-issuers
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
data:
  issuers.yaml: |
{{ tpl ( .Files.Get "files/issuers.yaml" ) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "certManager.name.crdInstall" . }}-orders
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
data:
  orders.yaml: |
{{ tpl ( .Files.Get "files/orders.yaml" ) . | indent 4 }}
{{- end }}
