{{- if .Values.crds.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "certManager.name.crdInstall" . }}"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    role: "{{ template "certManager.CRDInstallSelector" . }}"
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  - certificates
  - clusterissuers
  - issuers
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - acme.cert-manager.io
  resources:
  - challenges
  - orders
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "certManager.name.crdInstall" . }}
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "certManager.name.crdInstall" . }}"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    role: "{{ template "certManager.CRDInstallSelector" . }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "certManager.name.crdInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "certManager.name.crdInstall" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
