{{- if .Values.crds.install }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-6"
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "certManager.name.crdInstall" . }}"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    role: "{{ template "certManager.CRDInstallSelector" . }}"
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'configMap'
  - 'secret'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}
