{{- if .Values.crds.install }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "certManager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: crd-install
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
{{- end }}
