{{- if .Values.crds.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  labels:
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
  annotations:
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
{{- end }}
