checks:
  exclude:
  - "no-liveness-probe"
  - "no-read-only-root-fs"
  - "no-readiness-probe"
  - "required-annotation-email"
  - "required-label-owner"
  - "unset-cpu-requirements"
  - "unset-memory-requirements"
