apiVersion: v1
appVersion: 1.0.3
description: A Helm chart for cert-manager
engine: gotpl
home: https://github.com/giantswarm/cert-manager-app
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
name: cert-manager-app
sources:
- https://github.com/jetstack/cert-manager
annotations:
    application.giantswarm.io/values-schema: https://raw.githubusercontent.com/giantswarm/cert-manager-app/v[[ .Version ]]/helm/cert-manager-app/values.schema.json  
version: [[ .Version ]]