name: cert-manager

userID: 1000
groupID: 1000

global:
  image:
    registry: quay.io

image:
  name: giantswarm/cert-manager-controller
  tag: v0.9.0

resources:
  requests:
    cpu: 50m
    memory: 100Mi

controller:

  # AWS parameters to configure cert manager to work with Route53
  aws:

    # Role name used to authenticate cert manager against AWS API
    role: ""
