cainjector:
  extraArgs: []
  image:
    name: giantswarm/cert-manager-cainjector
    pullPolicy: IfNotPresent
    tag: v0.15.2
  loglevel: null
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
controller:
  defaultIssuer:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-giantswarm
  extraArgs: []
  image:
    name: giantswarm/cert-manager-controller
    pullPolicy: IfNotPresent
    tag: v0.15.2
  loglevel: null
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
global:
  image:
    registry: quay.io
  leaderElectionNamespace: kube-system
  name: cert-manager
  securityContext:
    groupID: 1000
    userID: 1000
prometheus:
  enabled: true
webhook:
  image:
    name: giantswarm/cert-manager-webhook
    pullPolicy: IfNotPresent
    tag: v0.15.2
  loglevel: null
  replicas: 1
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
  securePort: 10250
