name: cert-manager

global:
  image:
    registry: quay.io

image:
  controller:
    name: giantswarm/cert-manager-controller
    pullPolicy: IfNotPresent
    tag: v0.15.1
  kubectl:
    name: giantswarm/docker-kubectl
    pullPolicy: IfNotPresent
    tag: 1.16.4

resources:
  requests:
    cpu: 50m
    memory: 100Mi

securityContext:
  userID: 1000
  groupID: 1000
