# Default values for cert-manager-giantswarm-clusterissuer chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: cert-manager-giantswarm-clusterissuer

image:
  registry: docker.io
  repository: giantswarm/docker-kubectl
  tag: ""

# this should be higher than the default (6) in order to ensure
# that the job is not marked as failed if it runs too soon after
# the webhook pod has been created.
backoffLimit: 10

userID: 1000
groupID: 1000

resources:
  requests:
    cpu: 100m
    memory: 150Mi

# install
# Install the Giant Swarm ClusterIssuer named `letsencrypt-giantswarm`
install: true

acme:
  dns01:
    cloudflare:
      enabled: false
      # Cloudflare API token with sufficient scope to create/delete records.
      token: ""
    route53:
      enabled: false
      # route53 region.
      region: ""
      # route53 role to assume.
      role: ""
      # (optional) route53 hosted zone ID. Allows avoiding granting route53:ListHostedZonesByName.
      hostedZoneID: ""
      # route53 user access key.
      accessKeyID: ""
      # route53 user secret access key.
      secretAccessKey: ""
  http01:
    enabled: true
    ingressClass: ""
    ingress:
      name: ""
