apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "startupapicheck.fullname" . }}
  namespace: {{ include "cert-manager.namespace" . }}
  labels:
    app: {{ include "startupapicheck.name" . }}
    app.kubernetes.io/name: {{ include "startupapicheck.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "startupapicheck"
    {{- include "labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ include "startupapicheck.name" . }}
      app.kubernetes.io/name: {{ include "startupapicheck.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "startupapicheck"
      {{- include "labels" . | nindent 8 }}
  egress:
    - toEntities:
        - kube-apiserver
