apiVersion: batch/v1
kind: Job
metadata:
  name: waitforcilium
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 50
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: waitforcilium
      priorityClassName: system-cluster-critical
      containers:
        - name: wait-for-cilium-crds
          image: "quay.io/giantswarm/docker-kubectl:1.24.4"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsNonRoot: true
          command:
            - sh
          args:
            - -c
            - |
              kubectl wait --timeout=5m --for=condition=established crd ciliumnetworkpolicies.cilium.io
              kubectl wait --timeout=1m --for=condition=established crd ciliumclusterwidenetworkpolicies.cilium.io
