{{- if .Values.global.giantSwarmClusterIssuer.install }}
{{- if and (eq .Values.global.giantSwarmClusterIssuer.acmeSolver "dns01") (ne .Values.global.giantSwarmClusterIssuer.cloudflare.token "") }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: kube-system
type: Opaque
stringData:
  api-token: {{ .Values.global.giantSwarmClusterIssuer.cloudflare.token }}
{{- end }}
{{- end }}
