{{- define "clusterIssuer" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-giantswarm
spec:
  acme:
    # Email address used for ACME registration
    email: accounts@giantswarm.io
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-giantswarm
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    {{ if eq .Values.global.giantSwarmClusterIssuer.acmeSolver "dns01" }}
    - dns01:
        cloudflare:
          email: accounts@giantswarm.io
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
    {{ else }}
     - http01:
        ingress:
          class: nginx
    {{ end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-giantswarm
spec:
  selfSigned: {}
{{- end }}

{{- if .Values.global.giantSwarmClusterIssuer.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-1"
    {{- include "issuerAnnotations" . | nindent 4 }}
  labels:
    {{- include "issuerLabels" . | nindent 4 }}
data:
  clusterissuer: |
{{ include "clusterIssuer" . | indent 4 }}
{{- end }}
