apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "issuerLabels" . | nindent 4 }}
  annotations:
    {{- include "issuerAnnotations" . | nindent 4 }}
    helm.sh/hook-weight: "1"
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "issuerLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.global.securityContext }}
      securityContext:
        runAsUser: {{ .userID }}
        runAsGroup: {{ .groupID }}
        runAsNonRoot: {{ .runAsNonRoot }}
        seccompProfile:
          {{- toYaml .seccompProfile | nindent 10 }}
      {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        args:
        - apply
        - --filename
        - /data
        {{- with .Values.global.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.name }}
          subPath: clusterissuer.yaml
          mountPath: /data/clusterissuer.yaml
        resources: {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: {{ .Values.name }}
        configMap:
          name: {{ .Values.name }}
      restartPolicy: Never
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
