{{- if .Values.global.giantSwarmClusterIssuer.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-1"
    {{- include "issuerAnnotations" . | nindent 4 }}
  labels:
    {{- include "issuerLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  - clusterissuers
  verbs:
  - "create"
  - "delete"
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - "create"
  - "delete"
  - "get"
  - "patch"
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.name }}
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-2"
    {{- include "issuerAnnotations" . | nindent 4 }}
  labels:
    {{- include "issuerLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
