{{- if .Values.global.giantSwarmClusterIssuer.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook-weight": "-1"
    {{- include "issuerAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "issuerLabels" . | nindent 4 }}
{{- end }}
